mongo:
  container_name: mongo
  image: mongo:latest
  volumes:
    - ./data:/data/db
  ports:
    - "27017:27017"
app:
  container_name: app
  restart: always
  build: .
  ports:
    - "8080:8080"
  links:
    - mongo
  environment:
    - NODE_ENV=development